### PR TITLE
Parallelize all the datasets and run them on a schedule

### PR DESCRIPTION
**Pull request by jdangerx**
Only in sandbox, though. If the run works I'll get to work on the production credentials.

### CODE REVIEW

**Comment by jdangerx** [comment]
@zschira whee! Look at all the failures! I guess we need to add some more robust retrying logic + maybe fix some other bugs that I haven't dug into yet 😅 

I wonder if we could run some sort of "subsetted" version of this on sandbox as integration test...?

**Comment by zschira** [comment]
Oh no! It looks like most of these are timeouts or rate limiting problems. We're definitely going to need to investigate to make this more robust. I did notice one error I had meant to address in my last round of fixes, but I guess I forgot to get it in there: #55

**Comment by zschira** [comment]
Glad you're getting this retry logic worked out, I can't wait to see this PR with all green checkmarks!

**Comment by jdangerx** [comment]
Closing in favor of #59 .

**Pull request closed without merging**
